### ISSUE TITLE
ArgumentException (PCL_111) and InvalidProgramException (NET45) when resolving dynamically registered types

### ISSUE THREAD

**Issue by swlasse** [seesharper/LightInject#245]
We register a significant number of types by reflection. These types need factory functions to be created since few, if any, constructor parameters can be derived from the IoC container (i.e. they are explicit parameters). Parameters include value types also.

Ultimately, what we do is to create a "wrapper" lambda method over the single constructor that is in each type, and attempt to register these lambdas as factory methods (with parameters).

**Example**

We have a type `Foo` with a single ctor requiring two args. It is assumed `IBar` exists and is implemented by some other class (irrelevant for this example in any case).

```csharp
public class Foo : IFoo
{
    public Foo(IBar bar, string baz)
    {
        Bar = bar;
        Baz = baz;
    }
    public IBar Bar { get; private set; }
    public string Baz { get; private set; }
}
```

When we register `Foo` in the ServiceContainer we dynamically create factory methods using information about the ctor's arg types (from reflection), and prepends an `IServiceFactory` to create the lambda expression parameter list similar to this:

```csharp
(IServiceFactory factory, <ctor args>) => new TService(<ctor args>)
```

In other words, the resulting `Delegate` is a:

```csharp
Func<IServiceFactory, [ctor args], TService>
```

In the case above, the lambda expression would become:

```csharp
(IServiceFactory factory, IBar arg1, string arg2) => new Foo(arg1, arg2)
```

and the delegate would be of type:

```csharp
Func<IServiceFactory, IBar, string, Foo>
```

Unfortunately, these methods fail to build inside LightInject, as they are (re)wrapped and emitted. In particular, when we do:

```csharp
var iocFoo = _serviceContainer.GetInstance(typeof (Foo), typeof(Foo).Name, args) as Foo;
```

... we get the following exceptions:

**Compilation symbol: PCL_111**

```
System.ArgumentException was unhandled
  HResult=-2147024809
  Message=Method 'LightInjectDebug.Foo Invoke(LightInject.IServiceFactory, LightInjectDebug.IBar, System.String)' declared on type 'System.Func`4[LightInject.IServiceFactory,LightInjectDebug.IBar,System.String,LightInjectDebug.Foo]' cannot be called with instance of type 'LightInject.IServiceFactory'
  Source=System.Core
  StackTrace:
       at System.Linq.Expressions.Expression.ValidateCallInstanceType(Type instanceType, MethodInfo method)
       at System.Linq.Expressions.Expression.ValidateStaticOrInstanceMethod(Expression instance, MethodInfo method)
       at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
       at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, Expression[] arguments)
       at LightInject.ILGenerator.Emit(OpCode code, MethodInfo methodInfo) in C:\Some\Path\Projects\LightInjectDebug\LightInjectDebug\LightInject.cs:line 5483
       at LightInject.Emitter.<>c__DisplayClass17_0.<Emit>b__0(ILGenerator il) in C:\Some\Path\Projects\LightInjectDebug\LightInjectDebug\LightInject.cs:line 7600
       at LightInject.Emitter.Emit(OpCode code) in C:\Some\Path\Projects\LightInjectDebug\LightInjectDebug\LightInject.cs:line 7399
       at LightInject.EmitterExtensions.Return(IEmitter emitter) in C:\Some\Path\Projects\LightInjectDebug\LightInjectDebug\LightInject.cs:line 2206
       at LightInject.ServiceContainer.CreateDynamicMethodDelegate(Action`1 serviceEmitter) in C:\Some\Path\Projects\LightInjectDebug\LightInjectDebug\LightInject.cs:line 3494
       at LightInject.ServiceContainer.CreateDelegate(Type serviceType, String serviceName, Boolean throwError) in C:\Some\Path\Projects\LightInjectDebug\LightInjectDebug\LightInject.cs:line 4359
       at LightInject.ServiceContainer.CreateNamedDelegate(Tuple`2 key, Boolean throwError) in C:\Some\Path\Projects\LightInjectDebug\LightInjectDebug\LightInject.cs:line 4334
       at LightInject.ServiceContainer.GetInstance(Type serviceType, String serviceName, Object[] arguments) in C:\Some\Path\Projects\LightInjectDebug\LightInjectDebug\LightInject.cs:line 3044
       at LightInjectDebug.Program.Main() in C:\Some\Path\Projects\LightInjectDebug\LightInjectDebug\Program.cs:line 30
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

**Compilation symbol: NET45**
```
System.InvalidProgramException was unhandled
  HResult=-2146233030
  Message=JIT Compiler encountered an internal limitation.
  Source=LightInjectDebug
  StackTrace:
       at DynamicMethod(Object[] )
       at LightInject.ServiceContainer.GetInstance(Type serviceType, String serviceName, Object[] arguments) in C:\Some\Path\Projects\LightInjectDebug\LightInjectDebug\LightInject.cs:line 3049
       at LightInjectDebug.Program.Main() in C:\Some\Path\Projects\LightInjectDebug\LightInjectDebug\Program.cs:line 30
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
```

We target PCL (tested on both profiles 7 and 111), but the problem occurs on plain .NET 4.5 as well (as seen above).

I have included the console app we have used to track this down. **The sample app also contains further details on how we build the Linq Expressions and the resulting delegate we register with LightInject (using the `ServiceRegistration` type).**

The sample app uses a copy of `src\LightInject\LightInject\LightInject.cs` from the git repo where my local checkout is currently at commit: ccaa6bd74bcacf52d2e50ec611a5b7c5ea68cb5f

### Environment

IDE: Visual Studio 2015
Windows 8.1 Enterprise

### Sample App

Type: .NET 4.5.2 Console Application
Compilation symbols tried: `PCL_111` and `NET45` (both fails - though with different exceptions)

[LightInjectDebug.tar.gz.txt](https://github.com/seesharper/LightInject/files/78645/LightInjectDebug.tar.gz.txt)

**Please note:** When uploading the .zip file (which should be allowed here) I got the following error:

``Unfortunately, we don’t support that file type.  Choose Files Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.``

... googling a bit showed that other people are experiencing same issues with github's support for external files. Having tried .zip, .7z, tar.gz, etc. without any luck, I decided to upload the tar.gz file with a dumy .txt extension as a workaround - simply remove that and you should be able to unzip the solution.

**Comment by seesharper** [comment]
Very interesting indeed. I think it has something to do with the fact that you are feeding it a delegate that is kind of outside the context of the container. I will take a look at it. 
btw, I wish everybody were as thorough as  you when it comes to a sample application to demonstrate the problem :)

**Comment by seesharper** [comment]
It is related to closures. Looking into this now

**Comment by seesharper** [comment]
LightInject 4.0.4 has just been published to the official NuGet feed.

**Comment by swlasse** [comment]
@seesharper Amazing - thank you so much for a quick response and solution on this :)
