### ISSUE TITLE
GetAllInstances<>() throws System.ArgumentException when resolving more than 9 services for the same interface

### ISSUE THREAD

**Issue by swlasse** [seesharper/LightInject#257]
GetAllInstances<>() throws System.ArgumentException when resolving more than 9 services for the same interface.

**Sample App:**

```csharp
using System;
using System.Linq;
using LightInject;

namespace LightInjectDebug
{
    public class Program
    {
        public static void Main()
        {
            // Using LightInject 4.0.7
            var container = new ServiceContainer();
            container.Register<Foo0>();
            container.Register<Foo1>();
            container.Register<Foo2>();
            container.Register<Foo3>();
            container.Register<Foo4>();
            container.Register<Foo5>();
            container.Register<Foo6>();
            container.Register<Foo7>();
            container.Register<Foo8>();

            // Causes System.ArgumentException in
            // ILGenerator.Emit(OpCode code, Type type)
            // when creating an ArrayAccess expression
            // using a non-int32 type as index (in this
            // case, an sbyte)
            container.Register<Foo9>();

            var allInstances = container.GetAllInstances<IFoo>().ToList();
            Console.WriteLine(allInstances.Count);
            Console.ReadLine();
        }
    }

    public interface IFoo { }
    public class Foo0 : IFoo { }
    public class Foo1 : IFoo { }
    public class Foo2 : IFoo { }
    public class Foo3 : IFoo { }
    public class Foo4 : IFoo { }
    public class Foo5 : IFoo { }
    public class Foo6 : IFoo { }
    public class Foo7 : IFoo { }
    public class Foo8 : IFoo { }
    public class Foo9 : IFoo { }
}
```

**Exception:**

```
System.ArgumentException was unhandled
  HResult=-2147024809
  Message=Argument for array index must be of type Int32
  Source=System.Core
  StackTrace:
       at System.Linq.Expressions.Expression.ArrayAccess(Expression array, IEnumerable`1 indexes)
       at System.Linq.Expressions.Expression.ArrayAccess(Expression array, Expression[] indexes)
       at LightInject.ILGenerator.Emit(OpCode code, Type type) in C:\my\path\LightInject.cs:line 4845
       at LightInject.Emitter.<>c__DisplayClass14_0.<Emit>b__0(ILGenerator il) in C:\my\path\LightInject.cs:line 6920
       at LightInject.Emitter.Emit(OpCode code) in C:\my\path\LightInject.cs:line 6800
       at LightInject.EmitterExtensions.Return(IEmitter emitter) in C:\my\path\LightInject.cs:line 1563
       at LightInject.ServiceContainer.CreateDynamicMethodDelegate(Action`1 serviceEmitter) in C:\my\path\LightInject.cs:line 2907
       at LightInject.ServiceContainer.CreateDelegate(Type serviceType, String serviceName, Boolean throwError) in C:\my\path\LightInject.cs:line 3760
       at LightInject.ServiceContainer.CreateDefaultDelegate(Type serviceType, Boolean throwError) in C:\my\path\LightInject.cs:line 3723
       at LightInject.ServiceContainer.GetInstance(Type serviceType) in C:\my\path\LightInject.cs:line 2393
       at LightInject.ServiceContainer.GetInstance[TService]() in C:\my\path\LightInject.cs:line 2446
       at LightInject.ServiceContainer.GetAllInstances[TService]() in C:\my\path\LightInject.cs:line 2674
       at LightInjectDebug.Program.Main() in C:\my\path\Program.cs:line 30
...
```

**Proposed Solution:**

As I see it, the issue is that when the 10th service is registered, then, during `GetAllInstances<>()`, the array index `9` is pushed onto the evaluation stack using opcode `Ldc_I4_S`. This puts an `Expression.Constant(arg, typeof(sbyte))` onto the stack, which is then later used as array index (which is not allowed).

As it might be intented to treat `Ldc_I4_S` as an `Expression.Constant(arg, typeof(sbyte))` in other scenarios, I was thinking if it would make sense to do the following change in `ILGenerator.Emit(OpCode code, Type type)`?: 

```
public void Emit(OpCode code, Type type)
{
    if (code == OpCodes.Newarr)
    {
        stack.Push(Expression.NewArrayBounds(type, Pop(1)));
    }
    else if (code == OpCodes.Stelem)
    {
        var value = stack.Pop();

        // From
        // var index = stack.Pop();

        // To
        var index = Expression.Convert(stack.Pop(), typeof(int));

        var array = stack.Pop();
        var arrayAccess = Expression.ArrayAccess(array, index);

        var assignExpression = Expression.Assign(arrayAccess, value);
        expressions.Add(assignExpression);
    }
```

If you want, I can create a pull request with the above fix :)

**Environment:**

- VS2015 Update 1
- Windows 8.1 Enterprise x64
- LightInject 4.0.7 (raw source - d4ed883 )
- .NET 4.5.2

**Comment by seesharper** [comment]
The fix is now available on NuGet.

btw, while you fix most certainly would work, it would be solving it at the wrong level. The mistake is all on me not properly reading how the Ldc_I4_S instruction should work.

https://msdn.microsoft.com/en-us/library/system.reflection.emit.opcodes.ldc_i4_s(v=vs.110).aspx
"Pushes the supplied int8 value onto the evaluation stack as an int32, short form."

The mistake I made was that I forgot to cast the actual sbyte value to an int which effectively meant that we ended up with the wrong type on the stack.

**Comment by swlasse** [comment]
Hi Bernhard,

Thanks for a quick reply and solution to this issue. I was discussing this with a colleague, and we were quit excited to see at which level you would solve it, as it was a bit hard for us to derive all side effects by applying a general solution. But your solution definitely looks right :) Thanks for fixing this so "lightening" fast ;)

/Lasse

**Comment by seesharper** [comment]
You're welcome :)
