### ISSUE TITLE
Method not found: LightInject.Microsoft.DependencyInjection with v4.1.0

### ISSUE THREAD

**Issue by Droritos** [seesharper/LightInject#304]
On a **.net core app** I'm getting an exception of:
> Method not found: 'Void LightInject.IServiceRegistry.Register(System.Func`2, LightInject.ILifetime)'.

LightInject.Microsoft.DependencyInjection is working with v4.0.11.

**Comment by seesharper** [comment]
Make sure that you update LightInject.Microsoft.DependencyInjection to version 1.0.1

**Comment by geirsagberg** [comment]
The working version of LightInject.Microsoft.DependencyInjection is 1.1.0.

**Comment by Droritos** [comment]
@geirsagberg, I'm still getting the same exception of "Method not found" when trying to create the IServiceProvider with `container.CreateServiceProvider(services);`.

Did you test it?

If I try creating it with  `services.BuildServiceProvider()`, code **passes** the Startup phase, but getting an exception when a dependency is needed, for example HomeController needs ITimeManager:

Connection id ""0HKUHG1PUMNOF"": An unhandled exception was thrown by the application.
System.InvalidOperationException: Unable to resolve service for type 'Test.Time.ITimeManager' while attempting to activate 'Test.API.Controllers.Home.HomeController'.
   at Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.TypeActivatorCache.CreateInstance[TInstance](IServiceProvider serviceProvider, Type implementationType)
   at Microsoft.AspNetCore.Mvc.Controllers.DefaultControllerFactory.CreateController(ControllerContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAllActionFiltersAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeExceptionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware`1.<Invoke>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Server.Kestrel.Internal.Http.Frame`1.<RequestProcessingAsync>d__2.MoveNext()

**Comment by Droritos** [comment]
@geirsagberg, after updating, I'm still getting the same exception. Did you test it ?

**Comment by geirsagberg** [comment]
@Droritos you are right, I can reproduce it with 1.1.0. I might have some time tonight to check it out.

**Comment by geirsagberg** [comment]
Seems an old version was referenced in the project.json-file, made a PR https://github.com/seesharper/LightInject.Microsoft.DependencyInjection/pull/6

**Comment by seesharper** [comment]
Published to NuGet

**Comment by Droritos** [comment]
Works like a charm. Thank you!
