### ISSUE TITLE
Resolve fails on missing dependency

### ISSUE THREAD

**Issue by vegar** [seesharper/LightInject#333]
Have a look at the following exception:

```
Unable to resolve type: FLIS.BackgroundJobs.Common.ICheckSignicatExpiredJob, service name:

System.InvalidOperationException: Unable to resolve type: FLIS.BackgroundJobs.Common.ICheckSignicatExpiredJob, service name:  ---> System.InvalidOperationException: Unresolved dependency [Target Type: FLIS.BackgroundJobs.Scheduling.CheckSignicatExpiredJob], [Parameter: signingService(FLIS.Signing.Common.ISigningService)], [Requested dependency: ServiceType:FLIS.Signing.Common.ISigningService, ServiceName:] ---> System.InvalidOperationException: Unresolved dependency [Target Type: FLIS.Signing.Signicat.SignicatSigningService], [Parameter: config(FLIS.Signing.Signicat.SignicatConfiguration)], [Requested dependency: ServiceType:FLIS.Signing.Signicat.SignicatConfiguration, ServiceName:] ---> System.InvalidOperationException: No resolvable constructor found for Type: FLIS.Signing.Signicat.SignicatRetryPolicy
   at LightInject.MostResolvableConstructorSelector.Execute(Type implementingType) in C:\projects\lightinject\build\tmp\Net45\Binary\LightInject\LightInject.cs:line 5127
   at LightInject.TypeConstructionInfoBuilder.Execute(Registration registration) in C:\projects\lightinject\build\tmp\Net45\Binary\LightInject\LightInject.cs:line 5286
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at LightInject.ServiceContainer.EmitNewInstance(ServiceRegistration serviceRegistration, IEmitter emitter) in C:\projects\lightinject\build\tmp\Net45\Binary\LightInject\LightInject.cs:line 3291
   at LightInject.ServiceContainer.<>c__DisplayClass152_0.<CreateEmitMethodWrapper>b__0(IEmitter ms) in C:\projects\lightinject\build\tmp\Net45\Binary\LightInject\LightInject.cs:line 3122
   at LightInject.ServiceContainer.<>c__DisplayClass152_0.<CreateEmitMethodWrapper>b__0(IEmitter ms) in C:\projects\lightinject\build\tmp\Net45\Binary\LightInject\LightInject.cs:line 3122
   at LightInject.ServiceContainer.EmitPropertyDependency(IEmitter emitter, PropertyDependency propertyDependency, LocalBuilder instanceVariable) in C:\projects\lightinject\build\tmp\Net45\Binary\LightInject\LightInject.cs:line 3440
   at LightInject.ServiceContainer.EmitPropertyDependencies(ConstructionInfo constructionInfo, IEmitter emitter) in C:\projects\lightinject\build\tmp\Net45\Binary\LightInject\LightInject.cs:line 3515
   at LightInject.ServiceContainer.EmitNewInstanceUsingImplementingType(IEmitter emitter, ConstructionInfo constructionInfo, Action`1 decoratorTargetEmitMethod) in C:\projects\lightinject\build\tmp\Net45\Binary\LightInject\LightInject.cs:line 3346
   at LightInject.ServiceContainer.EmitNewInstance(ServiceRegistration serviceRegistration, IEmitter emitter) in C:\projects\lightinject\build\tmp\Net45\Binary\LightInject\LightInject.cs:line 3301
   at LightInject.ServiceContainer.<>c__DisplayClass152_0.<CreateEmitMethodWrapper>b__0(IEmitter ms) in C:\projects\lightinject\build\tmp\Net45\Binary\LightInject\LightInject.cs:line 3122
   at LightInject.ServiceContainer.EmitConstructorDependency(IEmitter emitter, Dependency dependency) in C:\projects\lightinject\build\tmp\Net45\Binary\LightInject\LightInject.cs:line 3421
   --- End of inner exception stack trace ---
   at LightInject.ServiceContainer.EmitConstructorDependency(IEmitter emitter, Dependency dependency) in C:\projects\lightinject\build\tmp\Net45\Binary\LightInject\LightInject.cs:line 3426
   at LightInject.ServiceContainer.EmitConstructorDependencies(ConstructionInfo constructionInfo, IEmitter emitter, Action`1 decoratorTargetEmitter) in C:\projects\lightinject\build\tmp\Net45\Binary\LightInject\LightInject.cs:line 3383
   at LightInject.ServiceContainer.EmitNewInstanceUsingImplementingType(IEmitter emitter, ConstructionInfo constructionInfo, Action`1 decoratorTargetEmitMethod) in C:\projects\lightinject\build\tmp\Net45\Binary\LightInject\LightInject.cs:line 3344
   at LightInject.ServiceContainer.EmitNewInstance(ServiceRegistration serviceRegistration, IEmitter emitter) in C:\projects\lightinject\build\tmp\Net45\Binary\LightInject\LightInject.cs:line 3301
   at LightInject.ServiceContainer.<>c__DisplayClass152_0.<CreateEmitMethodWrapper>b__0(IEmitter ms) in C:\projects\lightinject\build\tmp\Net45\Binary\LightInject\LightInject.cs:line 3122
   at LightInject.ServiceContainer.EmitConstructorDependency(IEmitter emitter, Dependency dependency) in C:\projects\lightinject\build\tmp\Net45\Binary\LightInject\LightInject.cs:line 3421
   --- End of inner exception stack trace ---
   at LightInject.ServiceContainer.EmitConstructorDependency(IEmitter emitter, Dependency dependency) in C:\projects\lightinject\build\tmp\Net45\Binary\LightInject\LightInject.cs:line 3426
   at LightInject.ServiceContainer.EmitConstructorDependencies(ConstructionInfo constructionInfo, IEmitter emitter, Action`1 decoratorTargetEmitter) in C:\projects\lightinject\build\tmp\Net45\Binary\LightInject\LightInject.cs:line 3383
   at LightInject.ServiceContainer.EmitNewInstanceUsingImplementingType(IEmitter emitter, ConstructionInfo constructionInfo, Action`1 decoratorTargetEmitMethod) in C:\projects\lightinject\build\tmp\Net45\Binary\LightInject\LightInject.cs:line 3344
   at LightInject.ServiceContainer.EmitNewInstance(ServiceRegistration serviceRegistration, IEmitter emitter) in C:\projects\lightinject\build\tmp\Net45\Binary\LightInject\LightInject.cs:line 3301
   at LightInject.ServiceContainer.<>c__DisplayClass152_0.<CreateEmitMethodWrapper>b__0(IEmitter ms) in C:\projects\lightinject\build\tmp\Net45\Binary\LightInject\LightInject.cs:line 3122
   at LightInject.ServiceContainer.CreateDynamicMethodDelegate(Action`1 serviceEmitter) in C:\projects\lightinject\build\tmp\Net45\Binary\LightInject\LightInject.cs:line 3044
   at LightInject.ServiceContainer.CreateDelegate(Type serviceType, String serviceName, Boolean throwError) in C:\projects\lightinject\build\tmp\Net45\Binary\LightInject\LightInject.cs:line 3909
   --- End of inner exception stack trace ---
   at LightInject.ServiceContainer.CreateDelegate(Type serviceType, String serviceName, Boolean throwError) in C:\projects\lightinject\build\tmp\Net45\Binary\LightInject\LightInject.cs:line 3914
   at LightInject.ServiceContainer.CreateDefaultDelegate(Type serviceType, Boolean throwError) in C:\projects\lightinject\build\tmp\Net45\Binary\LightInject\LightInject.cs:line 3872
   at LightInject.ServiceContainer.TryGetInstance(Type serviceType) in C:\projects\lightinject\build\tmp\Net45\Binary\LightInject\LightInject.cs:line 2742
```

To break it down, `ICheckSignicatExpirdJob` cannot be resolved, because it's implementation `CheckSignicatExpiredJob` is dependent on `ISigningService`, which implementation `SignicatSigningService` is dependent on `SignicatConfiguration`, which cannot be resolved, because no resolvable constructor was found for the type `SignicatRetryPolicy`.

The constructor of `SignicatRetryPolicy` takes a couple of parameters which is not available from the IoC, so no surprise there. What surprises me is that it tries to resolve `SignicatRetryPolicy` at all. 

`SignicatConfiguration` has only one constructor, and that constructor is parameter-less. 
I *do* have a public writable property of type `SignicatRetryPolicy`, but the documentation clearly states that  

> LightInject* considers all read/write properties a dependency, but implements a loose strategy around property dependencies, meaning that it will NOT* throw an exception in the case of an unresolved property dependency.

I've tried to recreate the issue in a simple command line application without luck.

The relevant service registrations is as follow:

```
            container.Register<ISigningService, SignicatSigningService>();
            container.Register<SignicatConfiguration>();
            container.Register<ICheckSignicatExpiredJob, CheckSignicatExpiredJob>();
```

If I change the `SignicatConfiguration` to `container.RegisterInstance(new SignicatConfiguration());`, it works like a charm. 
Changing the property setter to private also solves the issue. 

So what's going on here?

I'm currently using Lightinject v4.1.1.

**Comment by seesharper** [comment]
The only thing I can think of here is that you don't have a ICompositionRoot implementation and therefore LightInject tries to scan the assembly from which the service is registered. It will then try to inject the property dependency and since some of its constructor parameters are unknow, LightInject will throw an exception. My recommendation here is to avoid assembly scanning and explicitly register all services within a composition root

**Comment by vegar** [comment]
Because IF it finds the proper type, it WILL try so resolve it?
But it still shouldn't throw, though...?

**Comment by seesharper** [comment]
btw 

```
container.RegisterInstance(new SignicatConfiguration());
```

this works because you are now basically creating the instance yourself and hence no property injection

**Comment by vegar** [comment]
So `unresolved` in `will NOT* throw an exception in the case of an unresolved property dependency` means `type not known` and not `tried, but could not instantiate`. 

Yes, the `RegisterInstance`-thing was there to rule out that the exception was thrown because the 'missing'/'failed' dependency was required elsewhere.

**Comment by vegar** [comment]
Btw - I guess this will be the case of constructor injection as well?

```
class Foo : IFoo {
   public Foo(IBar bar){ }
   public Foo(IBar bar, IFiz fiz){ }
}
```

If both `IBar` and `IFiz` is registered, but `IFiz`-implementation has a unknown dependency, the container will fail resolving `IFoo` instead of 'falling back' to the less complex constructor?

**Comment by seesharper** [comment]
That is correct 👍
