### ISSUE TITLE
System.InvalidOperationException: Attempt to create a scoped instance without a current scope

### ISSUE THREAD

**Issue by Balbhimpsl** [seesharper/LightInject#399]
Hi,
I am writing the integration test using Nunit and in business logic Microsoft.Practices.ServiceLocator being used.
 I  initialised ServiceLocator as below
ServiceLocator.SetLocatorProvider(() => new LightInjectServiceLocator(webApiContainer)); where webApiContainer is Lightinject 5.1.0 ServiceContainer.
I am using in-memory Httpserver to run the controllers in httpContext. Controller runs asynchronously using async/await.
As per documentation on git hub, I set the below property after enable web API on container and did not see any improvement. 
 webApiContainer.ScopeManagerProvider = new PerLogicalCallContextScopeManagerProvider();
Specific test  if i run alone, it is running fine .If I run it in Parallel with other test Iget following error. 

Microsoft.Practices.ServiceLocation.ActivationException: Activation error occured while trying to get instance of type IUserProvider, key "" ---> System.InvalidOperationException: **Attempt to create a scoped instance without a current scope**.
   at EPPS.LightInject.PerScopeLifetime.GetInstance(Func`1 createInstance, Scope scope) in D:\EM\EPPS\Feature\EPPS.LightInject\LightInject.cs:line 5514
   at DynamicMethod(Object[] )
   at EPPS.LightInject.ServiceContainer.GetInstance(Type serviceType) in D:\EM\EPPS\Feature\EPPS.LightInject\LightInject.cs:line 2794
   at EPPS.LightInject.ServiceLocation.LightInjectServiceLocator.DoGetInstance(Type serviceType, String key) in D:\EM\EPPS\Feature\EPPS.LightInject\ServiceLocation\LightInject.ServiceLocation.cs:line 61
   at Microsoft.Practices.ServiceLocation.ServiceLocatorImplBase.GetInstance(Type serviceType, String key) in c:\Home\Chris\Projects\CommonServiceLocator\main\Microsoft.Practices.ServiceLocation\ServiceLocatorImplBase.cs:line 49
   --- End of inner exception stack trace ---
   at Microsoft.Practices.ServiceLocation.ServiceLocatorImplBase.GetInstance(Type serviceType, String key) in c:\Home\Chris\Projects\CommonServiceLocator\main\Microsoft.Practices.ServiceLocation\ServiceLocatorImplBase.cs:line 53
   at Microsoft.Practices.ServiceLocation.ServiceLocatorImplBase.GetInstance[TService]() in c:\Home\Chris\Projects\CommonServiceLocator\main\Microsoft.Practices.ServiceLocation\ServiceLocatorImplBase.cs:line 90
   at Elli.EPPS.Integration.Common.BusinessObjects.Loan.get_User() in D:\EM\EPPS\Feature\Elli.EPPS.Integration\Common\BusinessObjects\Loan.cs:line 142
   at Elli.EPPS.Integration.Domain.LockRates.LockRatesDomain.<GeneratePriceGrid>d__22.MoveNext() in D:\EM\EPPS\Feature\Elli.EPPS.Integration\Domain\LockRates\LockRatesDomain.cs:line 328
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Elli.EPPS.Integration.Domain.LockRates.LockRatesDomain.<LockRate>d__20.MoveNext() in D:\EM\EPPS\Feature\Elli.EPPS.Integration\Domain\LockRates\LockRatesDomain.cs:line 251
   at Elli.EPPS.Integration.Domain.LockRates.LockRatesDomain.<LockRate>d__20.MoveNext() in D:\EM\EPPS\Feature\Elli.EPPS.Integration\Domain\LockRates\LockRatesDomain.cs:line 271
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Elli.EPPS.Integration.Domain.LockRates.LockRatesDomain.<GetLockRates>d__19.MoveNext() in D:\EM\EPPS\Feature\Elli.EPPS.Integration\Domain\LockRates\LockRatesDomain.cs:line 149
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Elli.EPPS.Service.Controllers.RatesController.<PostRatesLock>d__10.MoveNext() in D:\EM\EPPS\Feature\Elli.EPPS.Service\Controllers\RatesController.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()

**Comment by seesharper** [comment]
Create a minimal repro of this and put it up on GitHub and we will PR a solution there 👍

**Comment by Balbhimpsl** [comment]
Hi Bernhard,
Thanks for the quick reply.As suggested, I have attached minimal repro. 
Steps to run (reproduce)
Extract attached Zip.
Open solution
Build the solution
Click "Run all" in Test explorer
Open log file from C:\temp\DemoLog_{yyyy.MM.dd}.text. It will have the exception details.

[LightInjectServiceLocatorIssueRepro.zip](https://github.com/seesharper/LightInject/files/1535347/LightInjectServiceLocatorIssueRepro.zip)

**Comment by Balbhimpsl** [comment]
Hi Bernhard,
Any updates on this. I am waiting for your response.

Thanks and regards
Balbhim

**Comment by Balbhimpsl** [comment]
Hi Bernhard,
Could you please update on this.

**Comment by ZOXEXIVO** [comment]
I have Command and Query dispatchers. If i execute some command or query in middeware - it's throw this exception

**Comment by ZOXEXIVO** [comment]
ASP.NET Core 2.0

I have QueryDispatcher and CommandDispatcher registered as Singletons.
Each dispatcher contains injected Scoped DbContexts.

In my middleware i access this dispatchers from context.RequestServices.GetService
After success call of QueryDispatcher.Execute next request to CommandDispatcher breaks with 
_System.InvalidOperationException: Attempt to create a scoped instance without a current scope_
