### ISSUE TITLE
Lazy<T> is not working with named service

### ISSUE THREAD

**Issue by VishmayS** [seesharper/LightInject#427]
I've a faced a strange issue

**Case 1**
I've one interface with two concrete classes IUserDatail, UserDatail and NewUserDatail
   ```
     serviceRegistry.Register<IUserDatail, UserDatail>("UserDatail",new PerContainerLifetime());
        serviceRegistry.Register<IUserDatail, NewUserDatail>("NewUserDatail", new PerContainerLifetime());
```
Now
```
userDatail = Container.GetInstance<Lazy<Interfaces.IUserData>>("NewUserDatail");
userDatail.Value ;
```

Thows expecption that it tried to resolve using "" service name

The exception
```
Unable to resolve type: Interfaces.IUserDatail, service name: 
   at LightInject.ServiceContainer.CreateDelegate(Type serviceType, String serviceName, Boolean throwError)
   at LightInject.ServiceContainer.CreateDefaultDelegate(Type serviceType, Boolean throwError)
   at LightInject.ServiceContainer.GetInstance(Type serviceType)
   at LightInject.ServiceFactoryExtensions.GetInstance[TService](IServiceFactory factory)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at LITest.Business.User.GetUser(Int32 userId) in C:\Users\...\User.cs:line 24
      at DynamicMethod(Object , Object[] )
   at LightInject.Interception.TargetInvocationInfo.Proceed() in C:\projects\lightinject-interception\build\tmp\netstandard11\Binary\LightInject.Interception\LightInject.Interception.cs:line 673
   at LightInject.Wcf.ServiceInterceptor.Invoke(IInvocationInfo invocationInfo) in ... Net45\Binary\LightInject.Wcf\LightInject.Wcf.cs:line 354
  
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)

```
**Case 2**
If i make One service default in same situation of case1, like  
```
serviceRegistry.Register<IUserDatail, UserDatail>(new PerContainerLifetime());
 serviceRegistry.Register<IUserDatail, NewUserDatail>("NewUserDatail", new PerContainerLifetime());
```
and 
```
userDatail = Container.GetInstance<Lazy<Interfaces.IUserDatail>>("NewUserDatail");
userDatail.Value;
```

It creates an instant of default class instead of NewUserDatail class

It works perfectly without Lazy<T> 
Can you please give us work around of it?

**Comment by VishmayS** [comment]
I solved it with function factories making it more dynamic
`serviceRegistry.Register<IUserFactory>(userfactory => new UserFactory(userfactory.GetInstance<IUserDatail>), new PerRequestLifeTime());`

Class:
```
   public UserFactory(Func<string, IUserDatail> createUserInstance)
   {
        _createUserInstance= createUserInstance;
   }
```

After that when i needed in same class
`_createUserInstance(nameofmyclass)`
and then used Lazy instance of IUserFactory.

**Comment by henrihs** [comment]
My solution wasn't working too well afterall. By registering the instance wrapped in a `Lazy`, the container won't dispose the instance when the container is disposed.

Your solution won't work either, as I need my registration to be a singleton (the actual instance I'm registering is a `HttpClient`). I'll try to create my own `DisposableLazy<T>` implementation to deal with this issue.

**Comment by VishmayS** [comment]
I think the solutions are correct for this problem if it worked with regular classes.
HttpClient is a special case, it is self disposing and it also disposes related messages and handlers after usages.
So i can say that it is for one time use and should be recreated for new uses.
Not only http clients but also input messages needs to be re instance.
So you can try with other classes to confirm
