### ISSUE TITLE
LightInject integration issue

### ISSUE THREAD

**Issue by n-sidorov** [seesharper/LightInject#432]
I am trying to use LightInject as IoC container in [Orleans Silo ](https://github.com/dotnet/orleans )and on startup it throws an error `Common Language Runtime detected an invalid program`.

I am not entirely sure on which side the issue is (Orleans does some assembly loading stuff and this looks like related to assembly mismatch).

The very root cause is that that LightInject can't resolve `IOptionsFormatter<>` (which may be separate issue), throws an error and then it lead to "invalid program" exception (with missing exception about root cause). I've got this when I added `LightInject` library as a source.

Tested with:
* Microsoft.Orleans.Server 2.0.3
* LightInject 5.1.5
* LightInject.Microsoft.DependencyInjection 2.0.7

Application targets `netcoreapp2.1` (also tested with `netcoreapp2.0` target).

Integration code looks like this:
```csharp
var container = new LightInject.ServiceContainer(opts);
var siloBuilder = new SiloHostBuilder()
    .UseServiceProviderFactory(services =>
    {
        return container.CreateServiceProvider(services);
    })
```

Full stack:
```
at DynamicMethod(Object[] )
at LightInject.Microsoft.DependencyInjection.PerRootScopeLifetime.CreateScopedInstance(Func`1 createInstance)
at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
at DynamicMethod(Object[] )
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
at Orleans.Runtime.SiloOptionsLogger.OnStart(CancellationToken token) in D:\build\agent\_work\18\s\src\Orleans.Runtime\OptionsLogger\OptionsLogger.cs:line 22
at Orleans.LifecycleExtensions.Observer.OnStart(CancellationToken ct)
at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.OnStart(CancellationToken ct) in D:\build\agent\_work\18\s\src\Orleans.Runtime\Lifecycle\SiloLifecycleSubject.cs:line 70
at Orleans.LifecycleSubject.WrapExecution(CancellationToken ct, Func`2 action) in D:\build\agent\_work\18\s\src\Orleans.Core\Lifecycle\LifecycleSubject.cs:line 103
at Orleans.LifecycleSubject.OnStart(CancellationToken ct) in D:\build\agent\_work\18\s\src\Orleans.Core\Lifecycle\LifecycleSubject.cs:line 49
```
Dotnet info:
```
> dotnet --info                                     
.NET Core SDK (reflecting any global.json):         
 Version:   2.1.300                                 
 Commit:    adab45bf0c                              
                                                    
Runtime Environment:                                
 OS Name:     Windows                               
 OS Version:  10.0.15063                            
 OS Platform: Windows                               
 RID:         win10-x64                             
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\  
                                                    
Host (useful for support):                          
  Version: 2.1.0                                    
  Commit:  caa7b7e2ba                               
```
Full solution that can reproduce the issue can be found here:
https://github.com/n-sidorov/OreansLightInjectIssueRepro

**Comment by seesharper** [comment]
Thanks for reporting this.Looking into it

**Comment by seesharper** [comment]
For now you can try this

```
 var opts = new LightInject.ContainerOptions
            {
                EnablePropertyInjection = false,
                LogFactory = _ => (msg) => lightInjectLogger.LogDebug(msg.Message),
                EnableVariance = false,
                DefaultServiceSelector = services => services.Last()
            };
```
