### ISSUE TITLE
Version 6.3.0 is not compatible with latest LightInject.Annotation 1.1.0

### ISSUE THREAD

**Issue by kemsky** [seesharper/LightInject#524]
Looks like adding optional `EnableOptionalArguments` broke it.

```
System.MissingMethodException: Method not found: 'Void LightInject.MostResolvableConstructorSelector..ctor(System.Func`3<System.Type,System.String,Boolean>)'.
   at LightInject.Annotation.AnnotatedConstructorSelector..ctor(Func`3 canGetInstance)
   at LightInject.AnnotationExtension.EnableAnnotatedConstructorInjection(ServiceContainer serviceContainer) in C:\projects\lightinject-annotation\build\tmp\Net46\Binary\LightInject.Annotation\LightInje
ct.Annotation.cs:line 94
   at XXXXX.Web.InjectionConfig.Configure(IApplicationConfiguration applicationConfiguration) in D:\Dev\Projects\XXXXX\XXXXX\App_Start\InjectionConfig.cs:line 17
   at XXXXX.Web.Startup.Configuration(IAppBuilder app) in D:\Dev\Projects\XXXXX\XXXXX\Startup.cs:line 71
```

**Comment by seesharper** [comment]
Ah, that is a breaking change indeed. Bump to 6.3.1 to fix this 👍😀

**Comment by kemsky** [comment]
Thanks!
