### ISSUE TITLE
System.InvalidOperationException: Stack empty in Configure

### ISSUE THREAD

**Issue by IPFSD** [seesharper/LightInject#526]
Hello

I faced an error when both Steeltoe and Lightinject are installed in the same project. Code that I have:

Program.cs:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LightInject.Microsoft.AspNetCore.Hosting;
using LightInject.Microsoft.DependencyInjection;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Steeltoe.Discovery.Client;

namespace WebApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .AddServiceDiscovery()
                .UseServiceProviderFactory(new LightInjectServiceProviderFactory())
                .ConfigureWebHostDefaults(webBuilder => { webBuilder.UseLightInject().UseStartup<Startup>(); });
    }
}
```

Startup.cs:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LightInject;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.HttpsPolicy;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;
using Steeltoe.Common.Http.Discovery;
using Steeltoe.Common.LoadBalancer;
using Steeltoe.Discovery.Client;
using WebApplication.Controllers;

namespace WebApplication
{
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllers();
            services.AddDiscoveryClient(Configuration);
            services.AddSingleton<ILoadBalancer, RandomLoadBalancer>();
            services
                .AddHttpClient("test", c =>
                {
                    c.BaseAddress = new Uri("https://TEST-SERVICE/");
                })
                .AddHttpMessageHandler<DiscoveryHttpMessageHandler>()
                .AddRandomLoadBalancer();
        }

        public void ConfigureContainer(IServiceContainer container)
        {
        }

        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseAuthorization();

            app.UseDiscoveryClient();

            app.UseEndpoints(endpoints => { endpoints.MapControllers(); });
        }
    }
}
```

I get runtime error in `app.UseDiscoveryClient();`:
```
System.InvalidOperationException: Unable to resolve type: Steeltoe.Discovery.Eureka.EurekaDiscoveryClient, service name: 
 ---> System.InvalidOperationException: Stack empty.
   at System.Collections.Generic.Stack`1.ThrowForEmptyStack()
   at System.Collections.Generic.Stack`1.Pop()
   at LightInject.Emitter.Emit(OpCode code, ConstructorInfo constructor)
   at LightInject.ServiceContainer.EmitNewInstanceUsingImplementingType(IEmitter emitter, ConstructionInfo constructionInfo, Action`1 decoratorTargetEmitMethod)
   at LightInject.ServiceContainer.EmitNewInstance(ServiceRegistration serviceRegistration, IEmitter emitter)
   at LightInject.ServiceContainer.EmitNewInstanceWithDecorators(ServiceRegistration serviceRegistration, IEmitter emitter)
   at LightInject.ServiceContainer.<>c__DisplayClass205_0.<ResolveEmitMethod>b__2(IEmitter ms)
   at LightInject.ServiceContainer.CreateDynamicMethodDelegate(Action`1 serviceEmitter)
   at LightInject.ServiceContainer.CreateInstanceDelegateIndex(Action`1 emitMethod)
   at LightInject.ServiceContainer.<>c__DisplayClass206_0.<EmitLifetime>b__4(ServiceRegistration _)
   at LightInject.LazyConcurrentDictionary`2.<>c__DisplayClass2_1.<GetOrAdd>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at LightInject.LazyConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at LightInject.ServiceContainer.EmitLifetime(ServiceRegistration serviceRegistration, Action`1 emitMethod, IEmitter emitter)
   at LightInject.ServiceContainer.<>c__DisplayClass205_0.<ResolveEmitMethod>b__1(IEmitter methodSkeleton)
   at LightInject.ServiceContainer.<>c__DisplayClass162_0.<CreateEmitMethodWrapper>b__0(IEmitter ms)
   at LightInject.ServiceContainer.CreateDynamicMethodDelegate(Action`1 serviceEmitter)
   at LightInject.ServiceContainer.CreateDelegate(Type serviceType, String serviceName, Boolean throwError)
   --- End of inner exception stack trace ---
   at LightInject.ServiceContainer.CreateDelegate(Type serviceType, String serviceName, Boolean throwError)
   at LightInject.ServiceContainer.CreateDefaultDelegate(Type serviceType, Boolean throwError)
   at LightInject.ServiceContainer.TryGetInstance(Type serviceType, Scope scope)
   at LightInject.Scope.TryGetInstance(Type serviceType)
   at LightInject.Microsoft.DependencyInjection.LightInjectServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Steeltoe.Discovery.Client.DiscoveryServiceCollectionExtensions.<>c.<AddEurekaServices>b__12_0(IServiceProvider p)
   at LightInject.Microsoft.DependencyInjection.DependencyInjectionContainerExtensions.<>c__DisplayClass10_0`1.<CreateTypedFactoryDelegate>b__0(IServiceFactory serviceFactory)
   at DynamicMethod(Object[] , Scope )
   at DynamicMethod(Object[] , Scope )
   at LightInject.ServiceContainer.TryGetInstance(Type serviceType, Scope scope)
   at LightInject.Scope.TryGetInstance(Type serviceType)
   at LightInject.Microsoft.DependencyInjection.LightInjectServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Steeltoe.Discovery.Client.DiscoveryApplicationBuilderExtensions.UseDiscoveryClient(IApplicationBuilder app)
   at WebApplication.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in WebApplication\Startup.cs:line 64
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Steeltoe.Discovery.Client.DiscoveryClientStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at WebApplication.Program.Main(String[] args) in WebApplication\Program.cs:line 19
```

Everything works perfectly with built-in container. I used following packages:

```
<PackageReference Include="LightInject" Version="6.3.1" />
<PackageReference Include="LightInject.Microsoft.AspNetCore.Hosting" Version="2.3.0" />
<PackageReference Include="LightInject.Microsoft.DependencyInjection" Version="3.3.0" />
```

Any ideas?

**Comment by seesharper** [comment]
Hi and thanks for reporting this.

Could you push this repro onto GitHub and I'll have a look?

**Comment by seesharper** [comment]
@IPFSD I am not able to reproduce this. I am going to need a "working" example to debug this

**Comment by seesharper** [comment]
Never mind. I found it 👍

**Comment by IPFSD** [comment]
Any updates?

**Comment by seesharper** [comment]
Bump to latest version of LightInject. That should fix the problem 👍

**Comment by IPFSD** [comment]
Tested with Lightinject 6.3.2 - the problem is gone. Thank you!
