### ISSUE TITLE
CanGetInstance throws System.ArgumentNullException when called with an unregistered serviceType and null serviceName

### ISSUE THREAD

**Issue by mesakomarevich** [seesharper/LightInject#578]
As stated in the title, calling `CanGetInstance(serviceType, serviceName)` where `serviceType` has not yet been registered and `serviceName = null` will result in a `System.ArgumentNullException`. 

This problem occurs with `LightInject` version 6.4.0-6.6.1

Stack trace is as follows:
```
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.ThrowHelper.ThrowArgumentNullException(String name)
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
   at LightInject.ServiceContainer.GetRegisteredEmitMethod(Type serviceType, String serviceName)
   at LightInject.ServiceContainer.GetEmitMethod(Type serviceType, String serviceName)
   at LightInject.ServiceContainer.CanGetInstance(Type serviceType, String serviceName)
```

I will be creating a PR with a fix ASAP.

**Comment by mesakomarevich** [comment]
Closing this issue as a resolution was merged long ago.
